Repository ironcore-dev/inventory, pull requests merged in 2024-06, with the labels that each got.

#210 Fix actions, we are now a public repository
  .github/workflows/auto-merge.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/publish-docker.yml
  .github/workflows/release-drafter.yml
  .github/workflows/size-labels.yaml
  .github/workflows/test.yaml
  Dockerfile
  hack/setup-git-redirect.sh
Labels: bug, enhancement, size/M

#212 deprecate outdated dependencies and upd
  Dockerfile
  cmd/benchmark-scheduler/command/root.go
  cmd/benchmark-scheduler/command/run.go
  cmd/benchmark-scheduler/command/run_flags.go
  cmd/benchmark-scheduler/main.go
  cmd/benchmark/main.go
  go.mod
  go.sum
  internal/benchmarks/benchmark.go
  internal/benchmarks/executor/executor.go
  internal/benchmarks/output/output.go
  internal/cgroup/cgroup.go
  internal/cgroup/v1.go
  internal/cgroup/v2.go
  internal/config/config.go
  internal/dispatcher/dispatcher.go
  internal/dispatcher/dispatcher_test.go
  internal/logger/log.go
  internal/provider/http.go
  internal/provider/http_test.go
  internal/provider/provider.go
  internal/smbiosinfo/smbios.go
  internal/updater/testdata/fio.json
  internal/updater/updater.go
  internal/updater/updater_test.go
  internal/worker/pool.go
  internal/worker/pool_test.go
  internal/worker/worker.go
  internal/worker/worker_test.go
  pkg/app/benchmark.go
  pkg/app/inventory.go
  pkg/app/nic_updater.go
  pkg/crd/builder.go
  pkg/crd/gateway_saver.go
  pkg/crd/kubeapi_saver.go
  pkg/crd/saver.go
  pkg/nic/svc.go
Labels: inventory, internal, size/XXL

#221 Drop benchmark from makefile build targets
  Makefile
Labels: bug, size/XS
